<?php

/**
 * functions.php
 *
 * Add sanity to Theme functions, moving them to thier own files in the /functions folder in both the parent and child
 * themes.
 *
 * @author     Jared Deschner
 * @since      File available since Release 1.0.0
 */

/****************************
 *  DO NOT EDIT THIS FILE
 *  Place all custom functions in the functions directory of this theme.
 ****************************/

if(!function_exists('kalapress_include_dir')) {
    function kalapress_include_dir( $path ) {
        $dir      = new RecursiveDirectoryIterator( $path );
        $iterator = new RecursiveIteratorIterator( $dir );
        foreach ( $iterator as $file ) {
            $fname = $file->getFilename();
            if ( preg_match( '%\.php$%', $fname ) ) {
                include_once( $file->getPathname() );
            }
        }
    }
}

// Include Parent Theme Functions
kalapress_include_dir(get_template_directory() . '/functions');

// Include Child Theme Functions
kalapress_include_dir(get_stylesheet_directory() . '/functions');
kalapress_include_dir(get_stylesheet_directory() . '/shortcodes');